Website/AuthorCourses/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path

from . import views
from .views import model_form_upload, loginPage, registerPage, logoutUser, home_view, item_list, \
    item_delete, search_contents, show_content, item_form

app_name = 'AuthorCourses'

urlpatterns = [
    path('', home_view, name='home'),
    path('upload/', model_form_upload, name='upload'),

    path('register/', registerPage, name='register'),
    path('login/', loginPage, name='login'),
    path('logout/', logoutUser, name='logout'),

    path('insert/', item_form, name='item_insert'),  # get and post req. for insert operation
    path('<int:id>/', item_form, name='item_update'),  # get and post req. for update operation
    path('delete/<int:id>/', item_delete, name='item_delete'),  # get req. for update operation
    path('list/', item_list, name='item_list'),  # get and post req. for display operation

    path('show_content/<content_id>', show_content, name='show_content'),
    path('search_contents/', search_contents, name='search_contents'),

    # url(r'^(?P<pk>\d+)/$', views.ContentDetail.as_view(), name='content_detail'),
    # url(r'^(?P<pk>\d+)/$', show_content, name='content_detail'),
]

if settings.DEBUG:  # To allow us to view the documents
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Website/Website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AuthorCourses.urls')),

    path('AuthorCourses/', include('django.contrib.auth.urls'))
]

Website/AuthorCourses/models.py
from django.db import models
from django.urls import reverse

from .validators import validate_file


# Create your models here.

class Category(models.Model):
    class Meta:
        verbose_name_plural = 'categories'

    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name


class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)

    document = models.FileField(upload_to='documents/', validators=[validate_file])

    def __str__(self):
        return "Name: " + self.description + " || Location: " + str(self.document)


class AllContents(models.Model):
    class Meta:
        verbose_name_plural = 'all contents'

    contentName = models.CharField(max_length=200)
    contentBody = models.CharField(max_length=100)
    contentSummary = models.CharField(max_length=60)

    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)

    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True)

    doc = models.ForeignKey(Document, on_delete=models.CASCADE)

    def __str__(self):
        return self.contentName

    def get_absolute_url(self):
        return reverse('AuthorCourses:item_update', kwargs={'id': self.id})

Website/AuthorCourses/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Document, AllContents


class SignUpForm(UserCreationForm):
    email = forms.EmailField(
        label='Email',
        max_length=254,
        widget=forms.EmailInput(
            attrs={
                "placeholder": "*Required",
                "class": "form-control"
            }
        )
    )

    username = forms.CharField(
        label='Username',
        max_length=30,
        min_length=5,
        required=True,
        widget=forms.TextInput(
            attrs={
                "placeholder": "*Required",
                "class": "form-control"
            }
        )
    )

    password1 = forms.CharField(
        label='Password',
        max_length=30,
        min_length=8,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "*Required",
                "class": "form-control"
            }
        )
    )

    password2 = forms.CharField(
        label='Confirm Password',
        max_length=30,
        min_length=8,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "*Required",
                "class": "form-control"
            }
        )
    )

    number = forms.CharField(
        label='Phone Number',
        required=True,
        max_length=10,
        min_length=10,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                "placeholder": "*Required",
                'pattern': '[0-9]+',
                'title': 'Enter numbers Only '
            }
        )
    )

    pincode = forms.CharField(
        required=True,
        max_length=6,
        min_length=6,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                "placeholder": "*Required",
                'pattern': '[0-9]+',
                'title': 'Enter numbers Only '
            }
        )
    )

    full_name = forms.CharField(
        required=True,
        max_length=20,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                "placeholder": "*Required",
                'pattern': '^([a-zA-Z]{2,}\\s[a-zA-Z]{2,}\\s?([a-zA-Z]{1,})?)',
                'title': 'Enter First Name and Last Name '
            }
        )
    )

    address = forms.CharField(
        label='Address',
        max_length=100,
        min_length=5,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )

    city = forms.CharField(
        label='City',
        max_length=30,
        min_length=3,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )

    state = forms.CharField(
        label='State',
        max_length=30,
        min_length=5,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )

    country = forms.CharField(
        label='Country',
        max_length=30,
        min_length=5,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'full_name', 'number', 'address', 'city', 'pincode',
                  'state', 'country')


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('description', 'document')


class ContentForm(forms.ModelForm):
    class Meta:
        model = AllContents
        fields = '__all__'
        labels = {
            'contentName': 'Title',
            'contentBody': 'Body',
            'contentSummary': 'Summary',
            'category': 'Category',
            'doc': 'Document',
            'author': 'Author',
        }

    def __init__(self, *args, **kwargs):
        self.entry = kwargs.pop('entry')  # the content entry instance
        super().__init__(*args, **kwargs)

    def save(self):
        cont = super().save(commit=False)
        cont.entry = self.entry
        cont.save()
        return cont

Website/AuthorCourses/views.py
# Create your views here.
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import SignUpForm, DocumentForm, ContentForm
from .models import AllContents


@login_required(login_url='AuthorCourses:login')
def home_view(request):
    return render(request, 'AuthorCourses/home.html')


def registerPage(request):
    if request.user.is_authenticated:
        return redirect('AuthorCourses:home')
    else:
        form = SignUpForm()
        if request.method == 'POST':
            form = SignUpForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + user)

                return redirect('AuthorCourses:login')

        context = {'form': form}
        return render(request, 'AuthorCourses/register.html', context)


def loginPage(request):
    if request.user.is_authenticated:
        return redirect('AuthorCourses:home')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            email = request.POST.get('email')
            password = request.POST.get('password')

            user = authenticate(request, username=username, email=email, password=password)

            if user is not None:
                login(request, user)
                return redirect('AuthorCourses:home')
            else:
                messages.success(request, 'Username OR password is incorrect')

        context = {}
        return render(request, 'AuthorCourses/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('AuthorCourses:login')


@login_required(login_url='AuthorCourses:login')
def model_form_upload(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('AuthorCourses:home')
    else:
        form = DocumentForm()
    return render(request, 'AuthorCourses/model_form_upload.html', {
        'form': form
    })


@login_required(login_url='AuthorCourses:login')
def item_list(request):
    context = {'item_list': AllContents.objects.all()}
    return render(request, "AuthorCourses/item_list.html", context)


@login_required(login_url='AuthorCourses:login')
def item_form(request, id=0):
    if request.method == "GET":
        if id == 0:
            form = ContentForm(entry=())
        else:
            item = AllContents.objects.get(pk=id)
            form = ContentForm(instance=item, entry=item)
        return render(request, "AuthorCourses/item_form.html", {'form': form})
    else:
        if id == 0:
            form = ContentForm(request.POST, entry=())
        else:
            item = AllContents.objects.get(pk=id)
            form = ContentForm(request.POST, instance=item, entry=item)
        if form.is_valid():
            form.save()
        return redirect('/list')


@login_required(login_url='AuthorCourses:login')
def item_delete(request, id):
    item = AllContents.objects.get(pk=id)
    item.delete()
    return redirect('/list')


@login_required(login_url='AuthorCourses:login')
def show_content(request, content_id):
    content = AllContents.objects.get(pk=content_id)
    return render(request, 'AuthorCourses/show_content.html',
                  {'content': content})


@login_required(login_url='AuthorCourses:login')
def search_contents(request):
    if request.method == "POST":
        searched = request.POST['searched']
        contents = AllContents.objects.filter(Q(contentName__contains=searched) | Q(contentBody__contains=searched) | Q(
            contentSummary__contains=searched) | Q(category__name__contains=searched))

        return render(request,
                      'AuthorCourses/search_contents.html',
                      {'searched': searched,
                       'contents': contents})
    else:
        return render(request,
                      'AuthorCourses/search_contents.html',
                      {})

Website/AuthorCourses/templates/AuthorCourses/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>User Register</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
</head>

<body>
    <div class="container">
        <div class="col-md-12 offset-md-0 mt-5">
            <div class="jumbotron">
                <h1 class="display-4">Content Items</h1>
                <ul class="lead display-8 font-bold">
                <a class="far float-right" href="{% url 'AuthorCourses:home' %}">Back to Home</a>
                </ul>
                <p class="lead font-italic">Content Project made in Python Django~Zeeshan </p>
                <hr class="my-4">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

Website/AuthorCourses/templates/AuthorCourses/home.html
{% load static %}


<style>
  .hello-msg{
    font-size: 18px;
    color: #000;
    margin-right: 20px;
  }
</style>


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="https://getbootstrap.com/docs/4.0/components/navbar/">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'AuthorCourses:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'AuthorCourses:item_list' %}">Contents</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0 p-3" method=POST action="{% url 'AuthorCourses:search_contents' %}">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="searched">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>

  <span class="hello-msg">Hello, {{request.user}}</span>
  <span ><a class="hello-msg" href="{% url 'AuthorCourses:logout' %}">Logout</a></span>

</nav>

<body id="bg" style="background-image: url('https://images.unsplash.com/photo-1432821596592-e2c18b78144f?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80'); background-repeat: no-repeat; background-size: cover; background-position: center; height: 100%;">

Website/AuthorCourses/templates/AuthorCourses/item_form.html
{% extends "AuthorCourses/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<form action="" method="post" autocomplete="off">
    {% csrf_token %}
    {{form.contentName|as_crispy_field}}
    {{form.author|as_crispy_field}}
    {{form.contentBody|as_crispy_field}}
    {{form.contentSummary|as_crispy_field}}
    <div class="row">
        <div class="col-md-4">
            {{form.category|as_crispy_field}}
        </div>
        <div class="col-md-8">
            {{form.doc|as_crispy_field}}
            <a href="{% url 'AuthorCourses:upload' %}" class="btn btn-primary btn-sm mb-3">
                <i class="fas fa-list"></i> Add Document
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <button type="submit" class="btn btn-success btn-block btn-lg"><i class="fas fa-plus-square"></i>
                Submit</button>
        </div>
        <div class="col-md-4">
            <a href="{% url 'AuthorCourses:item_list' %}" class="btn btn-secondary btn-block btn-lg">
                <i class="fas fa-list"></i> Back to list
            </a>
        </div>
    </div>

</form>
{% endblock content %}

Website/AuthorCourses/templates/AuthorCourses/item_list.html
{% extends "AuthorCourses/base.html" %}


{% block content %}
<table class="table table-borderless">
    <thead class="border-bottom font-weight-bold">
        <tr>
            <td>Title</td>
            <td>Author</td>
            <td>Body</td>
            <td>Summary</td>
            <td>Category</td>
            <td>Document</td>
            <td>
                <a href="{% url 'AuthorCourses:item_insert' %}" class="btn btn-outline-success">
                    <i class="fas fa-plus"></i> Add New
                </a>
            </td>
        </tr>
    </thead>
    <tbody>
        {% for item in item_list %}
            <tr>
                <td>{{item.contentName}}</td>
                <td>{{item.author}}</td>
                <td>{{item.contentBody}}</td>
                <td>{{item.contentSummary}}</td>
                <td>{{item.category}}</td>
                <td>{{item.doc}}</td>
                <td>
                    <a href="{% url 'AuthorCourses:item_update' item.id %}" class="btn d-block text-secondary px-0">
                        <i class="far fa-edit fa-lg"></i>
                    </a>
                    <form action="{% url 'AuthorCourses:item_delete' item.id %}" method="post" class="p-3">
                        {% csrf_token %}
                        <button type="submit" class="btn d-block">
                            <i class="far fa-trash-alt fa-lg text-danger float-right"></i>
                        </button>
                    </form>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

Website/AuthorCourses/templates/AuthorCourses/login.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;

		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope"></i></span>
							</div>
							<input type="text" name="email" placeholder="Email..." class="form-control">
						</div>
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{ messages }}</p>
				{% endfor %}


				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'AuthorCourses:register' %}" class="ml-2">Sign Up</a>
					</div>

				</div>
			</div>
		</div>
	</div>
</body>

</html>

Website/AuthorCourses/templates/AuthorCourses/logout.html
{% block content %}

<h3 class="mt-5 text-center">Logged Out {{ request.user }}</h3>

{% endblock content %}

Website/AuthorCourses/templates/AuthorCourses/model_form_upload.html
{% extends "AuthorCourses/base.html" %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

<!--  <p><a href="{% url 'AuthorCourses:home' %}">Return to home</a></p>-->
{% endblock content%}

Website/AuthorCourses/templates/AuthorCourses/search_contents.html
{% extends 'AuthorCourses/base.html' %}

{% block content %}
	<center>
	{% if searched %}
		<h1>You Searched For "{{ searched }}"</h1>
		<br/>
		{% for content in contents %}
			<a href="{% url 'AuthorCourses:show_content' content.id %}">{{ content }}</a><br/>
		{% endfor %}
	
	{% else %}
		<h1>Hey!You Forgot To Search For An Item...</h1>
	{% endif %}

	

	
	</center>
{% endblock content%}

Website/AuthorCourses/templates/AuthorCourses/show_content.html
{% extends 'AuthorCourses/base.html' %}

{% block content %}


<div class="card">
  <div class="card-header">
    Content Details:
  </div>
  <div class="card-body">
    <h5 class="card-title">{{ content }}</h5>
    <p class="card-text">
      <ul>

	<div class="card-header" >
        <li>Title:</li>
        <ul>{{ content.contentName }}</ul>
    </div>

      <div class="card-header" >
        <li>Author:</li>
        <ul>{{ content.author }}</ul>
    </div>

      <div class="card-header">
          <li>Body:</li>
          <ul>{{ content.contentBody }}</ul>
    </div>

      <div class="card-header">
          <li>Summary:</li>
          <ul>{{ content.contentSummary }}</ul>
    </div>

      <div class="card-header">
          <li>Category:</li>
          <ul>{{ content.category }}</ul>
    </div>

      <div class="card-header">
          <li>Document:</li>
          <ul><a href="{% url 'AuthorCourses:upload' %}">{{content.doc}}</a></ul>
    </div>

      </ul>



    </p>
  </div>
</div>



	</center>
{% endblock content%}